language: java
jdk:
- oraclejdk8

sudo: false
install: true

branches:
  only:
  - assignment09

script:
- pwd
- cd webapp
- ./gradlew build
- ./gradlew war
- ./gradlew test
- cd build/libs
- ls -al
- cd ../../..
- pwd
- ls -al

after_success:
- pwd
- ls -al
- mkdir codedeploy
- zip -r csye6225-web-app-$TRAVIS_JOB_NUMBER.zip webapp/build/libs/ROOT.war appspec.yml restartTomcat.sh
- ls -al
- mv csye6225-web-app-$TRAVIS_JOB_NUMBER.zip codedeploy/
- pwd 
- cd codedeploy
- ls -al
- pwd
- cd ..
- pwd
- ls -al

deploy:
- provider: s3
  local_dir: codedeploy
  bucket: $s3_bucket
  region: us-east-1
  skip_cleanup: true
  access_key_id: $access_key_id
  secret_access_key: $secret_access_key
  on:
    branch: assignment09
- provider: codedeploy
  access_key_id: $access_key_id
  secret_access_key: $secret_access_key
  bucket: $s3_bucket
  key: csye6225-web-app-$TRAVIS_JOB_NUMBER.zip
  bundle_type: zip
  application: $application
  deployment_group: $deployment_group
  region: us-east-1
  wait-until-deployed: true
  on:
    branch: assignment09

notifications:
 email:
    recipients:
    - yao.jiaw@husky.neu.edu
    on_success: always
    on_failure: always
