version: 0.0
os: linux

files:
  - source: ./appspec.yml
    destination: /home/ubuntu
  - source: ./restartTomcat.sh
    destination: /home/ubuntu
  - source: ./webapp/build/libs/ROOT.war
    destination: /var/lib/tomcat8/webapps


